trigger:
- main

pool:
  name: 'COMP367-Windows' 

variables:
  nodeVersion: '18.x' 
  authServiceDir: 'auth-service'
  authUiDir: 'auth-ui'
  communityServiceDir: 'community-service'
  communityUiDir: 'community-ui'
  hostDir: 'host' 

stages:
- stage: Build_And_Install
  displayName: 'Install Dependencies and Build'
  jobs:
  - job: BuildAndInstall
    displayName: 'Install & Build Services, UIs, and Host'
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: $(nodeVersion)
      displayName: 'Install Node.js $(nodeVersion)'

    - script: |
        echo "Running npm ci for $(authServiceDir)..."
        npm ci
      displayName: 'Install Dependencies for $(authServiceDir)'
      workingDirectory: '$(System.DefaultWorkingDirectory)/$(authServiceDir)'
    
    - script: |
        echo "Running npm ci for $(communityServiceDir)..."
        npm ci
      displayName: 'Install Dependencies for $(communityServiceDir)'
      workingDirectory: '$(System.DefaultWorkingDirectory)/$(communityServiceDir)'

# FOR AB 249 auth-service
    - script: |
        echo "Running unit tests for $(authServiceDir)..."
        node --experimental-vm-modules node_modules/jest/bin/jest.js
      displayName: 'Run Tests for $(authServiceDir)'
      workingDirectory: '$(System.DefaultWorkingDirectory)/$(authServiceDir)'

# FOR AB 249 community-service
    - script: |
        echo "Running unit tests for $(communityServiceDir)..."
        node --experimental-vm-modules node_modules/jest/bin/jest.js
      displayName: 'Run Tests for $(communityServiceDir)'
      workingDirectory: '$(System.DefaultWorkingDirectory)/$(communityServiceDir)'


    - script: |
        echo "Running npm ci for $(authUiDir)..."
        npm ci
      displayName: 'Install Dependencies for $(authUiDir)'
      workingDirectory: '$(System.DefaultWorkingDirectory)/$(authUiDir)'

    - script: |
        echo "Building $(authUiDir)..."
        npm run build
      displayName: 'Build $(authUiDir)'
      workingDirectory: '$(System.DefaultWorkingDirectory)/$(authUiDir)'

    - script: |
        echo "Running npm ci for $(communityUiDir)..."
        npm ci
      displayName: 'Install Dependencies for $(communityUiDir)'
      workingDirectory: '$(System.DefaultWorkingDirectory)/$(communityUiDir)'

    - script: |
        echo "Building $(communityUiDir)..."
        npm run build
      displayName: 'Build $(communityUiDir)'
      workingDirectory: '$(System.DefaultWorkingDirectory)/$(communityUiDir)'

    - script: |
        echo "Running npm ci for $(hostDir)..."
        npm ci
      displayName: 'Install Dependencies for $(hostDir)'
      workingDirectory: '$(System.DefaultWorkingDirectory)/$(hostDir)'

    - script: |
        echo "Building $(hostDir)..."
        npm run build
      displayName: 'Build $(hostDir)'
      workingDirectory: '$(System.DefaultWorkingDirectory)/$(hostDir)'
    
  # FOR AB 257 - Publish Artifact for Host
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(System.DefaultWorkingDirectory)/$(hostDir)/dist'
        ArtifactName: 'host-dist'
        publishLocation: 'Container'
      displayName: 'Publish host build artifact (dist folder)'  
# For 259-- Deploy stages for the CD Pipeline
- stage: Deploy
  displayName: 'Deploy Stage'
  dependsOn: Build_And_Install
  jobs:
    - job: DeployHost
      displayName: 'Simulate Deploy for host'
      steps:
       - download: current
         artifact: host-dist

       - script: |
          echo "Simulating deployment of host-dist..."
          echo "Copied contents to simulated web server directory..."
          echo "Deployed at: http://localhost:5000 (simulated)"
         displayName: 'Simulate Deployment for Host'