trigger:
- main

pool:
  name: 'COMP367-Windows'

variables:
  nodeVersion: '18.20.8'
  authServiceDir: 'auth-service'
  authUiDir: 'auth-ui'

stages:
- stage: Build_And_Install
  displayName: 'Install Dependencies and Build'
  jobs:
  - job: BuildAndInstall 
    displayName: 'Install & Build Auth Service and Auth UI'
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: $(nodeVersion)
      displayName: 'Install Node.js $(nodeVersion)'

    - script: |
        echo "Running npm ci for $(authServiceDir)..."
        npm ci
      displayName: 'Install Dependencies for $(authServiceDir)'
      workingDirectory: '$(System.DefaultWorkingDirectory)/$(authServiceDir)'

    - script: |
        echo "Running npm ci for $(authUiDir)..."
        npm ci
      displayName: 'Install Dependencies for $(authUiDir)'
      workingDirectory: '$(System.DefaultWorkingDirectory)/$(authUiDir)'

    - script: |
        echo "Building $(authUiDir)..."
        npm run build
      displayName: 'Build $(authUiDir)'
      workingDirectory: '$(System.DefaultWorkingDirectory)/$(authUiDir)'