trigger:
- main

pool:
  name: 'COMP367-Windows'

variables:
  nodeVersion: '18.20.8'
  authServiceDir: 'auth-service'

stages:
- stage: Build_And_Test_Auth_Service
  displayName: 'Build Auth Service'
  jobs:
  - job: Build
    displayName: 'Build Node.js Service'
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: $(nodeVersion)
      displayName: 'Install Node.js $(nodeVersion)'

    - script: |
        echo "Navigating to auth-service directory..."
        cd auth-service
        echo "Running npm install..."
        npm install
      displayName: 'Install Dependencies for auth-service'
      workingDirectory: $(Build.SourcesDirectory)
  
    - script: |
        echo "Running tests with coverage for $(authServiceDir)..."
        cd $(authServiceDir)
        npm run test:coverage
      displayName: 'Run Unit Tests with Coverage for $(authServiceDir)'
      workingDirectory: $(Build.SourcesDirectory)

    - task: PublishTestResults@2
      inputs:
        testResultsFormat: 'JUnit' 
        testResultsFiles: '$(Build.SourcesDirectory)/$(authServiceDir)/junit.xml'
        failTaskOnFailedTests: true
      displayName: 'Publish Test Results'
      condition: succeededOrFailed()

    - task: PublishCodeCoverageResults@1
      inputs:
        codeCoverageTool: 'Cobertura'
        summaryFileLocation: '$(Build.SourcesDirectory)/$(authServiceDir)/coverage/cobertura-coverage.xml'
      displayName: 'Publish Code Coverage Results'
      condition: succeededOrFailed()

# --- Stages for other services, analysis, deployment will be added later ---

